stages:
  - build
  - test
  - deploy

badges:
  stage: build
  image: hackfeed/iu7quiz
  script:
    - anybadge --label=docker
      --value=$(wget -q https://registry.hub.docker.com/v1/repositories/hackfeed/iu7quiz/tags -O -  |
      sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  |
      awk -F':' '{print $3}' | awk 'END{print}') --file=docker.svg -o --color=#0000FF
    - anybadge --label=channel --value='on telegram' --file=telegram.svg -o --color=#00FFFF
    - anybadge --label=branch --value=${CI_COMMIT_REF_NAME} --file=branch.svg -o --color=#4C1
    - anybadge --label=license --value='BMSTU License v1.1' --file=license.svg -o --color=#FE7D37
  artifacts:
    paths:
      - ./*.svg
    when: always
    expire_in: 30 days
  only:
    - pushes
    - merge_requests
    - schedules

codestyle:
  stage: test
  image: hackfeed/iu7quiz
  script:
    - pylint --exit-zero $(find ./ -name \*.py) > pylintlog.txt
    - SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylintlog.txt)
    - anybadge --label=pylint --value=$SCORE --file=pylint.svg -o 2=red 4=orange 8=yellow 10=green
    - cat pylintlog.txt
  artifacts:
    paths:
      - pylint*
    when: always
    expire_in: 30 days
  only:
    - pushes
    - merge_requests
    - schedules
