version: "3"

services:
  bot:
    image: "hackfeed/iu7quiz"
    container_name: "iu7quizbot"
    command: sh -c "PYTHONPATH='.' python bot/iu7quizbot.py"
    env_file:
      - credentials.env
    depends_on:
      - db

  db:
    image: mongo:4.2
    container_name: "mongodb"
    env_file:
      - credentials.env
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/db:/data/db
    ports:
      - "27017-27019:27017-27019"
