version: "3"

services:
  bot:
    image: "hackfeed/iu7quiz"
    container_name: "iu7quizbot"
    command: sh -c "python bot.py"
    environment:
      - TOKEN=${TOKEN}
    depends_on:
      - db

  db:
    image: mongo:4.2
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017-27019:27017-27019"
